version: '2'

services:
  mongo:  
    image: mvertes/alpine-mongo:3.2.3
    volumes:
      - $DATABASE_LOCATION:/data/db

    ports:
      - "27017:27017"
    command: mongod --smallfiles
    network_mode: "host"
    
  backend:
    environment:
      - FIREBASE_CONFIG=$FIREBASE_CONFIG
      - PHOTOS_LOCATION=$PHOTOS_LOCATION
    volumes:
      - $PHOTOS_LOCATION:$PHOTOS_LOCATION
    network_mode: "host"
    ports:
      - "11001:11001"
    build:
      context: .
      dockerfile: Dockerfile-gobackend

  frontend:
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile-webui 
