version: '2'

services:
  mongo:  
    image: mvertes/alpine-mongo:3.2.3
    volumes:
      - $DATABASE_LOCATION:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles

  backend:
    environment:
      - PHOTOS_LOCATION=$PHOTOS_LOCATION
      - ADMIN_UID=FILL_ME
    volumes:
      - $PHOTOS_LOCATION:$PHOTOS_LOCATION
    ports:
      - "11001:11001"
    build:
      context: .
      dockerfile: Dockerfile-gobackend

  frontend:
    links:
      - backend
    build:
      context: .
      dockerfile: Dockerfile-webui 
      
